/*LISTADO DE LAS VIVIENDAS CON SU RESPECTIVO ESTADO Y SI ESTÁN DISPONIBLES.*/
SELECT vivienda.descviv AS DESCRIPCION,estado_vivienda.codestviv,estado_vivienda.descestviv AS ESTADO
FROM VIVIENDA 
INNER JOIN estado_vivienda ON estado_vivienda.codestviv = vivienda.codestviv;


/*LISTADO DE LOS DEPARTAMENTOS QUE SE VENCE LA MENSUALIDAD.*/
SELECT FECFINDETALQ AS "MENSUALIDAD FINAL" , vivienda.descviv AS VIVIENDA FROM DETALLE_ALQUILER
INNER JOIN VIVIENDA ON VIVIENDA.CODVIV = DETALLE_ALQUILER.CODVIV;

/*LISTA INQUILINOS QUE FALTAN PAGAR.*/
SELECT CODDETALQ, COSDETALQ,ESTDETALQ AS "FALTA PAGAR",PERSONA.NOMPER AS INQUILINO 
FROM DETALLE_ALQUILER
INNER JOIN ALQUILER ON alquiler.codalq = DETALLE_ALQUILER.codalq
INNER JOIN PERSONA ON PERSONA.CODPER = alquiler.codper;

/*LISTAR LOS PAGOS DE ALQUILER DE VIVIENDA FECHA  POR  MES Y AÑO*/
SELECT COSDETALQ AS PAGOS, alquiler.fecalq AS FECHA
FROM DETALLE_ALQUILER
INNER JOIN ALQUILER ON alquiler.codalq = DETALLE_ALQUILER.codalq;


/*LISTAR INQUILINO POR VIVIENDA  Y UBIGEO*/
SELECT PERSONA.NOMPER AS INQUILINO, 
ubigeo.disubi||' '||ubigeo.proubi||' '||ubigeo.depubi AS UBIGEO,
vivienda.descviv AS VIVIENDA
FROM PROPIETARIO
INNER JOIN UBIGEO ON UBIGEO.CODUBI = PROPIETARIO.CODUBI
INNER JOIN VIVIENDA ON VIVIENDA.CODVIV = PROPIETARIO.CODVIV
INNER JOIN PERSONA ON PERSONA.CODPER = PROPIETARIO.CODPER;


