--------------------------------------------------------
-- Archivo creado  - lunes-diciembre-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "CARGO" 
   (	"CODCAR" CHAR(3 BYTE), 
	"NOMCAR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CARGO"."CODCAR" IS 'CODIGO DE CARGO';
   COMMENT ON COLUMN "CARGO"."NOMCAR" IS 'NOMBRE DE CARGO';
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "DEPARTAMENTO" 
   (	"CODDEP" CHAR(3 BYTE), 
	"NOMDEP" VARCHAR2(100 BYTE), 
	"CODUBI" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEPARTAMENTO"."CODDEP" IS 'CODIGO DE DEPARTAMENTO';
   COMMENT ON COLUMN "DEPARTAMENTO"."NOMDEP" IS 'NOMBRE DE DEPARTAMENTO';
--------------------------------------------------------
--  DDL for Table DETALLE_DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "DETALLE_DEPARTAMENTO" 
   (	"CODDETDEP" CHAR(4 BYTE), 
	"FECINDETDEP" DATE, 
	"SALDETDEP" NUMBER(9,2), 
	"SEGPER" VARCHAR2(100 BYTE), 
	"CODDEP" CHAR(3 BYTE), 
	"CODCAR" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DETALLE_DEPARTAMENTO"."CODDETDEP" IS 'CODIGO DE DETALLE DEPARTAMENTO';
   COMMENT ON COLUMN "DETALLE_DEPARTAMENTO"."FECINDETDEP" IS 'FECHA DE INICIO DE DETALLE DEPARTAMENTO';
   COMMENT ON COLUMN "DETALLE_DEPARTAMENTO"."SALDETDEP" IS 'SALARIO DEL DETALLE DEPARTAMENTO';
   COMMENT ON COLUMN "DETALLE_DEPARTAMENTO"."SEGPER" IS 'SEGURO  DE LA PERSONA';
--------------------------------------------------------
--  DDL for Table DETALLE_FAMILIA
--------------------------------------------------------

  CREATE TABLE "DETALLE_FAMILIA" 
   (	"CODDETFAM" CHAR(4 BYTE), 
	"PARDETFAM" VARCHAR2(100 BYTE), 
	"CODPER" CHAR(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DETALLE_FAMILIA"."CODDETFAM" IS 'CODIGO DE DETALLE FAMILIAR';
   COMMENT ON COLUMN "DETALLE_FAMILIA"."PARDETFAM" IS 'PARENTESCO DETALLE FAMILIAR';
--------------------------------------------------------
--  DDL for Table DETALLE_PROYECTO
--------------------------------------------------------

  CREATE TABLE "DETALLE_PROYECTO" 
   (	"CODDETPRO" CHAR(4 BYTE), 
	"HORDETPRO" CHAR(10 BYTE), 
	"CODPRO" CHAR(3 BYTE), 
	"CODPER" CHAR(4 BYTE), 
	"CODRES" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DETALLE_PROYECTO"."CODDETPRO" IS 'CODIGO DE DETALLE DEL PROYECTO';
   COMMENT ON COLUMN "DETALLE_PROYECTO"."HORDETPRO" IS 'CANTIDAD DE HORAS DE TRABAJOS DEL PROYECTO';
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "PERSONA" 
   (	"CODPER" CHAR(4 BYTE), 
	"NOMPER" VARCHAR2(100 BYTE), 
	"APEPATPER" VARCHAR2(100 BYTE), 
	"APEMATPER" VARCHAR2(100 BYTE), 
	"FECNACPER" DATE, 
	"DNIPER" CHAR(8 BYTE), 
	"DIRPER" VARCHAR2(150 BYTE), 
	"SEXPER" CHAR(1 BYTE), 
	"CODUBI" CHAR(3 BYTE), 
	"CODUSU" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PERSONA"."CODPER" IS 'CODIGO DE PERSONA';
   COMMENT ON COLUMN "PERSONA"."NOMPER" IS 'NOMBRE ';
   COMMENT ON COLUMN "PERSONA"."APEPATPER" IS 'APELLIDO PATERNO';
   COMMENT ON COLUMN "PERSONA"."APEMATPER" IS 'APELLIDO MATERNO ';
   COMMENT ON COLUMN "PERSONA"."FECNACPER" IS 'FECHA DE NACIMIENTO';
   COMMENT ON COLUMN "PERSONA"."DNIPER" IS 'NUMERO DE DNI';
   COMMENT ON COLUMN "PERSONA"."DIRPER" IS 'DIRECCION DE LA PERSONA';
   COMMENT ON COLUMN "PERSONA"."SEXPER" IS 'SEXO ';
--------------------------------------------------------
--  DDL for Table PROYECTO
--------------------------------------------------------

  CREATE TABLE "PROYECTO" 
   (	"CODPRO" CHAR(3 BYTE), 
	"NOMPRO" VARCHAR2(150 BYTE), 
	"CODUBI" CHAR(3 BYTE), 
	"CODDEP" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PROYECTO"."CODPRO" IS 'CODIGO DEL PROYECTO';
   COMMENT ON COLUMN "PROYECTO"."NOMPRO" IS 'NOMBRE DEL PROYECTO';
--------------------------------------------------------
--  DDL for Table RESPONSABILIDAD
--------------------------------------------------------

  CREATE TABLE "RESPONSABILIDAD" 
   (	"CODRES" CHAR(3 BYTE), 
	"DESCRES" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "RESPONSABILIDAD"."CODRES" IS 'CODIGO DE RESPONSABILIDAD';
   COMMENT ON COLUMN "RESPONSABILIDAD"."DESCRES" IS 'DESCRIPCION DE RESPONSABILIDAD';
--------------------------------------------------------
--  DDL for Table UBIGEO
--------------------------------------------------------

  CREATE TABLE "UBIGEO" 
   (	"CODUBI" CHAR(3 BYTE), 
	"DISTUBI" VARCHAR2(100 BYTE), 
	"PROVUBI" VARCHAR2(100 BYTE), 
	"DEPTUBI" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "UBIGEO"."CODUBI" IS 'CODIGO DE UBIGEO';
   COMMENT ON COLUMN "UBIGEO"."DISTUBI" IS 'DISTRITO';
   COMMENT ON COLUMN "UBIGEO"."PROVUBI" IS 'PROVINCIA';
   COMMENT ON COLUMN "UBIGEO"."DEPTUBI" IS 'DEPARTAMENTO';
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "USUARIO" 
   (	"CODUSU" CHAR(3 BYTE), 
	"USUUSU" VARCHAR2(100 BYTE), 
	"PASSUSU" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "USUARIO"."CODUSU" IS 'CODIGO DE USUARIO';
   COMMENT ON COLUMN "USUARIO"."USUUSU" IS 'USUARIO';
   COMMENT ON COLUMN "USUARIO"."PASSUSU" IS 'CONTRASEÃƒâ€˜A DEL USUARIO';
REM INSERTING into TECNOFAST.CARGO
SET DEFINE OFF;
Insert into CARGO (CODCAR,NOMCAR) values ('C01','ADMINISTRADOR');
Insert into CARGO (CODCAR,NOMCAR) values ('C02','CONTADOR');
Insert into CARGO (CODCAR,NOMCAR) values ('C03','DISEÃ‘ADOR');
Insert into CARGO (CODCAR,NOMCAR) values ('C04','COLABORADOR');
Insert into CARGO (CODCAR,NOMCAR) values ('C05','PROGRAMADOR');
REM INSERTING into TECNOFAST.DEPARTAMENTO
SET DEFINE OFF;
Insert into DEPARTAMENTO (CODDEP,NOMDEP,CODUBI) values ('D01','AREA DE CONTABILIDAD','001');
Insert into DEPARTAMENTO (CODDEP,NOMDEP,CODUBI) values ('D02','AREA DE ADMINISTRACION','002');
Insert into DEPARTAMENTO (CODDEP,NOMDEP,CODUBI) values ('D03','AREA DE DISEÃ‘OS','003');
Insert into DEPARTAMENTO (CODDEP,NOMDEP,CODUBI) values ('D04','AREA DE PROGRAMACION','004');
Insert into DEPARTAMENTO (CODDEP,NOMDEP,CODUBI) values ('D05','AREA DE PROYECTOS','005');
REM INSERTING into TECNOFAST.DETALLE_DEPARTAMENTO
SET DEFINE OFF;
Insert into DETALLE_DEPARTAMENTO (CODDETDEP,FECINDETDEP,SALDETDEP,SEGPER,CODDEP,CODCAR) values ('DE01',to_date('10/10/90','DD/MM/RR'),'500,5','0001FFF','D01','C01');
Insert into DETALLE_DEPARTAMENTO (CODDETDEP,FECINDETDEP,SALDETDEP,SEGPER,CODDEP,CODCAR) values ('DE02',to_date('18/02/01','DD/MM/RR'),'600','656WDW','D02','C02');
Insert into DETALLE_DEPARTAMENTO (CODDETDEP,FECINDETDEP,SALDETDEP,SEGPER,CODDEP,CODCAR) values ('DE03',to_date('26/04/99','DD/MM/RR'),'605','DW5D5','D03','C03');
Insert into DETALLE_DEPARTAMENTO (CODDETDEP,FECINDETDEP,SALDETDEP,SEGPER,CODDEP,CODCAR) values ('DE04',to_date('02/02/05','DD/MM/RR'),'900','ED26WE1D94','D04','C04');
Insert into DETALLE_DEPARTAMENTO (CODDETDEP,FECINDETDEP,SALDETDEP,SEGPER,CODDEP,CODCAR) values ('DE05',to_date('09/12/17','DD/MM/RR'),'450','W2D9W49D','D05','C05');
REM INSERTING into TECNOFAST.DETALLE_FAMILIA
SET DEFINE OFF;
Insert into DETALLE_FAMILIA (CODDETFAM,PARDETFAM,CODPER) values ('DF01','TIO','PE01');
Insert into DETALLE_FAMILIA (CODDETFAM,PARDETFAM,CODPER) values ('DF02','PAPA','PE02');
Insert into DETALLE_FAMILIA (CODDETFAM,PARDETFAM,CODPER) values ('DF03','PRIMO','PE03');
Insert into DETALLE_FAMILIA (CODDETFAM,PARDETFAM,CODPER) values ('DF04','PAPÃ�','PE04');
Insert into DETALLE_FAMILIA (CODDETFAM,PARDETFAM,CODPER) values ('DF05','ABUELO','PE05');
REM INSERTING into TECNOFAST.DETALLE_PROYECTO
SET DEFINE OFF;
Insert into DETALLE_PROYECTO (CODDETPRO,HORDETPRO,CODPRO,CODPER,CODRES) values ('DP01','10:00AM   ','PR1','PE01','R01');
Insert into DETALLE_PROYECTO (CODDETPRO,HORDETPRO,CODPRO,CODPER,CODRES) values ('DP02','11:00AM   ','PR2','PE02','R02');
Insert into DETALLE_PROYECTO (CODDETPRO,HORDETPRO,CODPRO,CODPER,CODRES) values ('DP03','02:00PM   ','PR3','PE03','R03');
Insert into DETALLE_PROYECTO (CODDETPRO,HORDETPRO,CODPRO,CODPER,CODRES) values ('DP04','06:00PM   ','PR4','PE04','R04');
Insert into DETALLE_PROYECTO (CODDETPRO,HORDETPRO,CODPRO,CODPER,CODRES) values ('DP05','08:00PM   ','PR5','PE05','R05');
REM INSERTING into TECNOFAST.PERSONA
SET DEFINE OFF;
Insert into PERSONA (CODPER,NOMPER,APEPATPER,APEMATPER,FECNACPER,DNIPER,DIRPER,SEXPER,CODUBI,CODUSU) values ('PE01','JUAN','VALERIO','VALERIO',to_date('10/10/99','DD/MM/RR'),'85201256','LAS MALVINAS','M','001','U01');
Insert into PERSONA (CODPER,NOMPER,APEPATPER,APEMATPER,FECNACPER,DNIPER,DIRPER,SEXPER,CODUBI,CODUSU) values ('PE02','PEDRO','JORQUERA','CASTILLO',to_date('19/02/98','DD/MM/RR'),'95236520','LAS VENECAS PANAMERICANA 22','M','002','U02');
Insert into PERSONA (CODPER,NOMPER,APEPATPER,APEMATPER,FECNACPER,DNIPER,DIRPER,SEXPER,CODUBI,CODUSU) values ('PE03','LUIS','CALANGO','CARLENS',to_date('04/04/00','DD/MM/RR'),'44541089','LAS CALATITAS SUR','M','003','U03');
Insert into PERSONA (CODPER,NOMPER,APEPATPER,APEMATPER,FECNACPER,DNIPER,DIRPER,SEXPER,CODUBI,CODUSU) values ('PE04','PAMELA','BAUTISTA','GARCIA',to_date('09/12/90','DD/MM/RR'),'78502592','LAS LOMAS','F','004','U04');
Insert into PERSONA (CODPER,NOMPER,APEPATPER,APEMATPER,FECNACPER,DNIPER,DIRPER,SEXPER,CODUBI,CODUSU) values ('PE05','OSCAR','PELON','MILLER',to_date('05/10/82','DD/MM/RR'),'85236029','PANAMERICANA SUR','M','005','U05');
REM INSERTING into TECNOFAST.PROYECTO
SET DEFINE OFF;
Insert into PROYECTO (CODPRO,NOMPRO,CODUBI,CODDEP) values ('PR1','VENTAS DE SOFTWARE','001','D01');
Insert into PROYECTO (CODPRO,NOMPRO,CODUBI,CODDEP) values ('PR2','CAMPAÃ‘AS DE VIDEOJUEGOS','002','D02');
Insert into PROYECTO (CODPRO,NOMPRO,CODUBI,CODDEP) values ('PR3','CAMPAÃ‘A DE NAVIDAD','003','D03');
Insert into PROYECTO (CODPRO,NOMPRO,CODUBI,CODDEP) values ('PR4','CAMPAÃ‘A DE SOLIDARIDAD','004','D04');
Insert into PROYECTO (CODPRO,NOMPRO,CODUBI,CODDEP) values ('PR5','PROMOCION DE TECNOLOGIAS','005','D05');
REM INSERTING into TECNOFAST.RESPONSABILIDAD
SET DEFINE OFF;
Insert into RESPONSABILIDAD (CODRES,DESCRES) values ('R01','CUIDAR LA OFICINA DE SISTEMAS');
Insert into RESPONSABILIDAD (CODRES,DESCRES) values ('R02','CONTRATAR A UN EMPLEADO');
Insert into RESPONSABILIDAD (CODRES,DESCRES) values ('R03','CUIDAR EL AREA');
Insert into RESPONSABILIDAD (CODRES,DESCRES) values ('R04','CUIDAR EL ASEO EN LA OFICINA');
Insert into RESPONSABILIDAD (CODRES,DESCRES) values ('R05','LLEGAR TEMPRANO AL TRABAJO');
REM INSERTING into TECNOFAST.UBIGEO
SET DEFINE OFF;
Insert into UBIGEO (CODUBI,DISTUBI,PROVUBI,DEPTUBI) values ('001','SAN VICENTE ','CAÃ‘ETE','LIMA');
Insert into UBIGEO (CODUBI,DISTUBI,PROVUBI,DEPTUBI) values ('002','SAN LUIS','CAÃ‘ETE','LIMA');
Insert into UBIGEO (CODUBI,DISTUBI,PROVUBI,DEPTUBI) values ('003','CERRO AZUL','CAÃ‘ETE','LIMA');
Insert into UBIGEO (CODUBI,DISTUBI,PROVUBI,DEPTUBI) values ('004','QUILMANA','CAÃ‘ETE','LIMA');
Insert into UBIGEO (CODUBI,DISTUBI,PROVUBI,DEPTUBI) values ('005','ZUÃ‘IGA','CAÃ‘ETE','LIMA');
REM INSERTING into TECNOFAST.USUARIO
SET DEFINE OFF;
Insert into USUARIO (CODUSU,USUUSU,PASSUSU) values ('U01','USUJUAN','NFKJKJDBFJGSJFSF');
Insert into USUARIO (CODUSU,USUUSU,PASSUSU) values ('U02','USUPEDRO','DFSKJFHSGDJHG');
Insert into USUARIO (CODUSU,USUUSU,PASSUSU) values ('U03','USUSARA','DFNSDJGHSBDJFNO');
Insert into USUARIO (CODUSU,USUUSU,PASSUSU) values ('U04','USUCARLOS','SFJDSGFKSHKFHSKDHFKS');
Insert into USUARIO (CODUSU,USUUSU,PASSUSU) values ('U05','USULILY','ADKJASHFJKDSKGS5');
--------------------------------------------------------
--  DDL for Index UBIGEO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UBIGEO_PK" ON "UBIGEO" ("CODUBI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIO_PK" ON "USUARIO" ("CODUSU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_PROYECTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_PROYECTO_PK" ON "DETALLE_PROYECTO" ("CODDETPRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CARGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARGO_PK" ON "CARGO" ("CODCAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPONSABILIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESPONSABILIDAD_PK" ON "RESPONSABILIDAD" ("CODRES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEPARTAMENTO_PK" ON "DEPARTAMENTO" ("CODDEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROYECTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO_PK" ON "PROYECTO" ("CODPRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_FAMILIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_FAMILIA_PK" ON "DETALLE_FAMILIA" ("CODDETFAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_DEPARTAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETALLE_DEPARTAMENTO_PK" ON "DETALLE_DEPARTAMENTO" ("CODDETDEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERSONA_PK" ON "PERSONA" ("CODPER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DETALLE_PROYECTO
--------------------------------------------------------

  ALTER TABLE "DETALLE_PROYECTO" ADD CONSTRAINT "DETALLE_PROYECTO_PK" PRIMARY KEY ("CODDETPRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DETALLE_PROYECTO" MODIFY ("CODRES" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_PROYECTO" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_PROYECTO" MODIFY ("CODPRO" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_PROYECTO" MODIFY ("HORDETPRO" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_PROYECTO" MODIFY ("CODDETPRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UBIGEO
--------------------------------------------------------

  ALTER TABLE "UBIGEO" ADD CONSTRAINT "UBIGEO_PK" PRIMARY KEY ("CODUBI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "UBIGEO" MODIFY ("CODUBI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("CODUSU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USUARIO" MODIFY ("CODUSU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPONSABILIDAD
--------------------------------------------------------

  ALTER TABLE "RESPONSABILIDAD" ADD CONSTRAINT "RESPONSABILIDAD_PK" PRIMARY KEY ("CODRES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RESPONSABILIDAD" MODIFY ("CODRES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_FAMILIA
--------------------------------------------------------

  ALTER TABLE "DETALLE_FAMILIA" ADD CONSTRAINT "DETALLE_FAMILIA_PK" PRIMARY KEY ("CODDETFAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DETALLE_FAMILIA" MODIFY ("CODPER" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_FAMILIA" MODIFY ("CODDETFAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("CODDEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEPARTAMENTO" MODIFY ("CODUBI" NOT NULL ENABLE);
  ALTER TABLE "DEPARTAMENTO" MODIFY ("CODDEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROYECTO
--------------------------------------------------------

  ALTER TABLE "PROYECTO" ADD CONSTRAINT "PROYECTO_PK" PRIMARY KEY ("CODPRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROYECTO" MODIFY ("CODDEP" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO" MODIFY ("CODUBI" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO" MODIFY ("CODPRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("CODPER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PERSONA" MODIFY ("CODUSU" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("CODUBI" NOT NULL ENABLE);
  ALTER TABLE "PERSONA" MODIFY ("CODPER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "DETALLE_DEPARTAMENTO" ADD CONSTRAINT "DETALLE_DEPARTAMENTO_PK" PRIMARY KEY ("CODDETDEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DETALLE_DEPARTAMENTO" MODIFY ("CODCAR" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_DEPARTAMENTO" MODIFY ("CODDEP" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_DEPARTAMENTO" MODIFY ("SALDETDEP" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_DEPARTAMENTO" MODIFY ("FECINDETDEP" NOT NULL ENABLE);
  ALTER TABLE "DETALLE_DEPARTAMENTO" MODIFY ("CODDETDEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "CARGO" ADD CONSTRAINT "CARGO_PK" PRIMARY KEY ("CODCAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARGO" MODIFY ("CODCAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "DEPARTAMENTO_UBIGEO_FK" FOREIGN KEY ("CODUBI")
	  REFERENCES "UBIGEO" ("CODUBI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "DETALLE_DEPARTAMENTO" ADD CONSTRAINT "DETALLE_DEPARTAMENTO_CARGO_FK" FOREIGN KEY ("CODCAR")
	  REFERENCES "CARGO" ("CODCAR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_FAMILIA
--------------------------------------------------------

  ALTER TABLE "DETALLE_FAMILIA" ADD CONSTRAINT "DETALLE_FAMILIA_PERSONA_FK" FOREIGN KEY ("CODPER")
	  REFERENCES "PERSONA" ("CODPER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_PROYECTO
--------------------------------------------------------

  ALTER TABLE "DETALLE_PROYECTO" ADD CONSTRAINT "DETALLE_PROYECTO_PERSONA_FK" FOREIGN KEY ("CODPER")
	  REFERENCES "PERSONA" ("CODPER") ENABLE;
  ALTER TABLE "DETALLE_PROYECTO" ADD CONSTRAINT "DETALLE_PROYECTO_PROYECTO_FK" FOREIGN KEY ("CODPRO")
	  REFERENCES "PROYECTO" ("CODPRO") ENABLE;
  ALTER TABLE "DETALLE_PROYECTO" ADD CONSTRAINT "DETALLE_PROYECTO_RESPO_FK" FOREIGN KEY ("CODRES")
	  REFERENCES "RESPONSABILIDAD" ("CODRES") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PERSONA" ADD CONSTRAINT "PERSONA_UBIGEO_FK" FOREIGN KEY ("CODUBI")
	  REFERENCES "UBIGEO" ("CODUBI") ENABLE;
  ALTER TABLE "PERSONA" ADD CONSTRAINT "PERSONA_USUARIO_FK" FOREIGN KEY ("CODUSU")
	  REFERENCES "USUARIO" ("CODUSU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROYECTO
--------------------------------------------------------

  ALTER TABLE "PROYECTO" ADD CONSTRAINT "PROYECTO_DEPARTAMENTO_FK" FOREIGN KEY ("CODDEP")
	  REFERENCES "DEPARTAMENTO" ("CODDEP") ENABLE;
  ALTER TABLE "PROYECTO" ADD CONSTRAINT "PROYECTO_UBIGEO_FK" FOREIGN KEY ("CODUBI")
	  REFERENCES "UBIGEO" ("CODUBI") ENABLE;
