 CREATE OR REPLACE FORCE VIEW "HISTCLINICA"."VW_LIST_MEDICO_ESPECIALIDAD" ("CODMED", "NOMMED", "APEMED", "DNIMED", "TELMED", "EMAMED", "PASMED", "NIVMED", "NOMESP", "NOMARE") AS 
  SELECT 
  CODMED,
  UPPER(NOMMED) AS NOMMED,
  UPPER(APEMED) AS APEMED,
  DNIMED,
  TELMED,
  EMAMED,
  PASMED, 
  NIVMED,
  UPPER(NOMESP) AS NOMESP,
  UPPER(NOMARE) AS NOMARE
FROM MEDICO
INNER JOIN ESPECIALIDAD ON MEDICO.CODESP =ESPECIALIDAD.CODESP
INNER JOIN AREA ON MEDICO.CODARE=AREA.CODARE
ORDER BY CODMED DESC;

 CREATE OR REPLACE FORCE VIEW "HISTCLINICA"."VW_LIST_MEDICO_ESPECIALIDAD" ("CODMED", "NOMMED", "APEMED", "DNIMED", "TELMED", "EMAMED", "PASMED", "NIVMED", "NOMESP", "NOMARE") AS 
  SELECT 
  CODMED,
  UPPER(NOMMED) AS NOMMED,
  UPPER(APEMED) AS APEMED,
  DNIMED,
  TELMED,
  EMAMED,
  PASMED, 
  NIVMED,
  UPPER(NOMESP) AS NOMESP,
  UPPER(NOMARE) AS NOMARE
FROM MEDICO
INNER JOIN ESPECIALIDAD ON MEDICO.CODESP =ESPECIALIDAD.CODESP
INNER JOIN AREA ON MEDICO.CODARE=AREA.CODARE
ORDER BY CODMED DESC;